### PR TITLE
Working Tests on des81

### PR DESCRIPTION
**Pull request by jhod0**
The repo now exists on des81 at `/data/des81.b/data/stronglens/PRODUCTION/Y6_CUTOUT_IMAGES/Y6_Bulk_Coadd_Cutouts`. I believe the permissions are such that everyone can access it, but feel free to test this.

The tests run in the `des20a` conda environment but do not all pass because there are no test coadd images in the right place.

### CODE REVIEW

**Comment by jhod0** [comment]
Linking #4

**Comment by rmorgan10** [comment]
I was able to run test_cutout.py and I can confirm 6 pass and 9 fail. I'm currently working on collecting some test images to determine if there will be any failures beyond the "missing images" failures

**Comment by rmorgan10** [comment]
I added image and psf files from DES2228+0001. After that we still had 6 pass and 9 fail. I fixed the bugs causing the failures in the repo on the DES machines and now 13 pass and 2 fail. The two that fail do so because the test has not been finished yet and raises a `NotImplementedError`.

I cannot commit and push the changes due to issues with permissions on the DES machines, so I'll need some help from @jhod0 to get the changes committed and pushed here.

**Comment by rmorgan10** [comment]
To resolve the permission errors, I overwrote the files on the main branch in a new clone of the repo with the files on this branch. The changes made for all tests have now been implemented, so I'm closing this pull request. Thanks @jhod0 for all your work on this!

**Comment by jhod0** [comment]
My DES account expired, so I am in the process of regaining access to it. Hopefully I'll be able to gain access to DES machines again soon

**Pull request closed without merging**
